//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterEC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MasterEntities : DbContext
    {
        public MasterEntities()
            : base("name=MasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PacientInfo> PacientInfoes { get; set; }
        public virtual DbSet<WeekMobility> WeekMobilities { get; set; }
        public virtual DbSet<TotalAlarm> TotalAlarms { get; set; }
        public virtual DbSet<PacientDrinkingInfo> PacientDrinkingInfoes { get; set; }
    
        public virtual ObjectResult<GetTotal_Result> GetTotal()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTotal_Result>("GetTotal");
        }
    
        public virtual ObjectResult<WeeklyMobility_Result> WeeklyMobility()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WeeklyMobility_Result>("WeeklyMobility");
        }
    
        public virtual ObjectResult<MonthlyMobility_Result> MonthlyMobility()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MonthlyMobility_Result>("MonthlyMobility");
        }
    
        public virtual ObjectResult<WeeklyMob_Result> WeeklyMob()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WeeklyMob_Result>("WeeklyMob");
        }
    
        public virtual ObjectResult<FinWeeklyMob_Result> FinWeeklyMob()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FinWeeklyMob_Result>("FinWeeklyMob");
        }
    
        public virtual ObjectResult<MonthlyMob_Result> MonthlyMob()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MonthlyMob_Result>("MonthlyMob");
        }
    
        public virtual ObjectResult<YearlyMob_Result> YearlyMob()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YearlyMob_Result>("YearlyMob");
        }
    
        public virtual ObjectResult<TodayMob_Result> TodayMob()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TodayMob_Result>("TodayMob");
        }
    
        public virtual ObjectResult<Nullable<int>> GetTotalAlarms()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetTotalAlarms");
        }
    
        public virtual ObjectResult<WeeklyHydratation_Result> WeeklyHydratation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WeeklyHydratation_Result>("WeeklyHydratation");
        }
    
        public virtual ObjectResult<MonthlyHydratation_Result> MonthlyHydratation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MonthlyHydratation_Result>("MonthlyHydratation");
        }
    
        public virtual ObjectResult<YearlyHydratation_Result> YearlyHydratation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<YearlyHydratation_Result>("YearlyHydratation");
        }
    
        public virtual ObjectResult<TodayHydratation_Result> TodayHydratation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TodayHydratation_Result>("TodayHydratation");
        }
    }
}
