//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterEC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacientDrinkingInfo
    {
        public int ID { get; set; }
        public Nullable<double> Confidence { get; set; }
        public Nullable<double> DrinkingProgress { get; set; }
        public string Drinking { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
